### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LagHD** [TuranicTeam/Altay#38]
#### Issue description
A TODO List I thought I'd write lol
## 

- [ ] Shulker Boxes
- [ ]  Enchantments
- [ ]  Boats
- [ ]  End & Nether Dimensions
- [ ] Vanilla like nether transfer 
- [x] fireworks
- [ ] ender crystals & totems
- [ ] MobAI
- [ ] Animal Riding

**Comment by shdudwns** [comment]
add redstone, riding horse,  Minecart, Multi-Core, Multi-thread,  pistone,

**Comment by BlockOfDevs** [comment]
Add Beacon

**Comment by VoltexYT** [comment]
Add automatic OP for Voltex 💃
